### ISSUE TITLE
Phase 1

### ISSUE THREAD

**Issue by carrieli15** [carrieli15/821Biostats_Final#1]
## Initial Setup and Planning
1. Create the GitHub repository.
2. Set up the project structure and initial files (e.g., .gitignore, requirements.txt).
3. Both partners discuss and finalize the project scope and requirements.

**Comment by AliciaXia222** [comment]
discussed about how we merge our code and avoid conflict, the solution is me creating class, instances and the output format first to restrict the thinking structure, then we can create each function for adding features later.
